apiVersion: v1
kind: Namespace
metadata:
  name: munich
spec:
  finalizers:
  - kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mes
  namespace: munich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mes
  template:
    metadata:
      labels:
        app: mes
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: mes
        image: ghcr.io/digitaltwinconsortium/manufacturingontologies:main
        imagePullPolicy: Always
        env:
        - name: StationType
          value: "MES"
        - name: ProductionLineName
          value: "munich"
        - name: OPCUA_USERNAME
          value: "myUsername"
        - name: OPCUA_PASSWORD
          value: "myPassword"
